-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_b1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_b1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110010000000000", 1 => "1010100000000000", 2 => "1111000000000000", 3 => "0001010000000000", 
    4 => "0100100000000000", 5 => "1101110000000000", 6 => "1011100000000000", 7 => "0100000000000000", 
    8 => "0011110000000000", 9 => "0011000000000000", 10 => "0010110000000000", 11 => "1000010000000000", 
    12 => "1011100000000000", 13 => "0000000000000000", 14 => "0000000000000000", 15 => "0011110000000000", 
    16 => "1011100000000000", 17 => "0000000000000000", 18 => "0001100000000000", 19 => "1001110000000000", 
    20 => "0100100000000000", 21 => "1010100000000000", 22 => "0000100000000000", 23 => "1001000000000000", 
    24 => "0111100000000000", 25 => "0110010000000000", 26 => "1111000000000000", 27 => "0011100000000000", 
    28 => "0010010000000000", 29 => "1111100000000000", 30 => "0101110000000000", 31 => "0101100000000000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

