// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="object_detect_nnbw_object_detect_nnbw,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=36,HLS_SYN_DSP=0,HLS_SYN_FF=4958,HLS_SYN_LUT=3319,HLS_VERSION=2024_2}" *)

module object_detect_nnbw (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [63:0] output_r;
wire   [31:0] length_r;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [0:0] icmp_ln34_reg_918;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state15;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state22;
reg   [31:0] length_r_read_reg_686;
reg   [63:0] output_r_read_reg_692;
reg   [63:0] input_r_read_reg_697;
wire   [0:0] icmp_ln34_fu_489_p2;
wire   [63:0] zext_ln34_fu_498_p1;
wire  signed [62:0] p_cast_fu_503_p4;
reg   [62:0] p_cast_reg_927;
reg   [62:0] trunc_ln1_reg_937;
wire    ap_CS_fsm_state11;
reg   [9:0] local_input_address0;
reg    local_input_ce0;
reg    local_input_we0;
wire   [15:0] local_input_q0;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_ap_done;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_ap_idle;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_ap_ready;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWID;
wire   [31:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWUSER;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WVALID;
wire   [15:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WDATA;
wire   [1:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WSTRB;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WLAST;
wire   [0:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WID;
wire   [0:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WUSER;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARID;
wire   [31:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARUSER;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_RREADY;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_BREADY;
wire   [9:0] grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_address0;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_ce0;
wire    grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_we0;
wire   [15:0] grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_d0;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_done;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_idle;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_ready;
wire   [9:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_local_input_address0;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_local_input_ce0;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6465_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6465_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6363_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6363_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6261_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6261_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6159_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6159_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6057_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6057_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5955_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5955_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5853_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5853_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5751_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5751_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5649_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5649_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5547_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5547_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5445_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5445_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5343_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5343_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5241_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5241_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5139_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5139_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5037_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5037_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4935_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4935_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4833_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4833_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4731_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4731_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4629_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4629_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4527_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4527_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4425_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4425_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4323_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4323_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4221_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4221_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4119_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4119_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4017_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4017_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3915_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3915_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3813_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3813_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3711_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3711_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_369_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_369_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_357_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_357_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_345_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_345_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_333_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_333_out_ap_vld;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_idle;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_ready;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_3_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_3_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_2_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_2_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_1_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_1_out_ap_vld;
wire   [15:0] grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_out;
wire    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_out_ap_vld;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_ap_done;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_ap_idle;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_ap_ready;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWID;
wire   [31:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWUSER;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WVALID;
wire   [15:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WDATA;
wire   [1:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WSTRB;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WLAST;
wire   [0:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WID;
wire   [0:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WUSER;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARID;
wire   [31:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARUSER;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_RREADY;
wire    grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_BREADY;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
reg   [63:0] gmem_0_AWADDR;
reg   [31:0] gmem_0_AWLEN;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
reg   [63:0] gmem_0_ARADDR;
reg   [31:0] gmem_0_ARLEN;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [15:0] gmem_0_RDATA;
wire   [9:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg    grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start_reg;
reg   [21:0] ap_NS_fsm;
wire    ap_NS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire  signed [63:0] p_cast_cast_fu_512_p1;
wire  signed [63:0] sext_ln70_fu_660_p1;
reg    ap_block_state2_io;
wire  signed [31:0] icmp_ln34_fu_489_p0;
wire  signed [62:0] sext_ln34_fu_495_p1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_block_state11_on_subcall_done;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start_reg = 1'b0;
#0 grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start_reg = 1'b0;
#0 grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start_reg = 1'b0;
#0 grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start_reg = 1'b0;
end

object_detect_nnbw_local_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
local_input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(local_input_address0),
    .ce0(local_input_ce0),
    .we0(local_input_we0),
    .d0(grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_d0),
    .q0(local_input_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_1 grp_object_detect_nnbw_Pipeline_1_fu_324(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start),
    .ap_done(grp_object_detect_nnbw_Pipeline_1_fu_324_ap_done),
    .ap_idle(grp_object_detect_nnbw_Pipeline_1_fu_324_ap_idle),
    .ap_ready(grp_object_detect_nnbw_Pipeline_1_fu_324_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .p_cast_cast(p_cast_reg_927),
    .local_input_address0(grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_address0),
    .local_input_ce0(grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_ce0),
    .local_input_we0(grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_we0),
    .local_input_d0(grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_d0),
    .length_r(length_r_read_reg_686)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2 grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start),
    .ap_done(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_done),
    .ap_idle(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_idle),
    .ap_ready(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_ready),
    .local_input_address0(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_local_input_address0),
    .local_input_ce0(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_local_input_ce0),
    .local_input_q0(local_input_q0),
    .hidden_6465_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6465_out),
    .hidden_6465_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6465_out_ap_vld),
    .hidden_6363_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6363_out),
    .hidden_6363_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6363_out_ap_vld),
    .hidden_6261_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6261_out),
    .hidden_6261_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6261_out_ap_vld),
    .hidden_6159_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6159_out),
    .hidden_6159_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6159_out_ap_vld),
    .hidden_6057_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6057_out),
    .hidden_6057_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6057_out_ap_vld),
    .hidden_5955_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5955_out),
    .hidden_5955_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5955_out_ap_vld),
    .hidden_5853_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5853_out),
    .hidden_5853_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5853_out_ap_vld),
    .hidden_5751_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5751_out),
    .hidden_5751_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5751_out_ap_vld),
    .hidden_5649_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5649_out),
    .hidden_5649_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5649_out_ap_vld),
    .hidden_5547_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5547_out),
    .hidden_5547_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5547_out_ap_vld),
    .hidden_5445_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5445_out),
    .hidden_5445_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5445_out_ap_vld),
    .hidden_5343_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5343_out),
    .hidden_5343_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5343_out_ap_vld),
    .hidden_5241_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5241_out),
    .hidden_5241_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5241_out_ap_vld),
    .hidden_5139_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5139_out),
    .hidden_5139_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5139_out_ap_vld),
    .hidden_5037_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5037_out),
    .hidden_5037_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5037_out_ap_vld),
    .hidden_4935_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4935_out),
    .hidden_4935_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4935_out_ap_vld),
    .hidden_4833_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4833_out),
    .hidden_4833_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4833_out_ap_vld),
    .hidden_4731_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4731_out),
    .hidden_4731_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4731_out_ap_vld),
    .hidden_4629_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4629_out),
    .hidden_4629_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4629_out_ap_vld),
    .hidden_4527_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4527_out),
    .hidden_4527_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4527_out_ap_vld),
    .hidden_4425_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4425_out),
    .hidden_4425_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4425_out_ap_vld),
    .hidden_4323_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4323_out),
    .hidden_4323_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4323_out_ap_vld),
    .hidden_4221_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4221_out),
    .hidden_4221_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4221_out_ap_vld),
    .hidden_4119_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4119_out),
    .hidden_4119_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4119_out_ap_vld),
    .hidden_4017_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4017_out),
    .hidden_4017_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4017_out_ap_vld),
    .hidden_3915_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3915_out),
    .hidden_3915_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3915_out_ap_vld),
    .hidden_3813_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3813_out),
    .hidden_3813_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3813_out_ap_vld),
    .hidden_3711_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3711_out),
    .hidden_3711_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3711_out_ap_vld),
    .hidden_369_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_369_out),
    .hidden_369_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_369_out_ap_vld),
    .hidden_357_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_357_out),
    .hidden_357_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_357_out_ap_vld),
    .hidden_345_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_345_out),
    .hidden_345_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_345_out_ap_vld),
    .hidden_333_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_333_out),
    .hidden_333_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_333_out_ap_vld)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3 grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start),
    .ap_done(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done),
    .ap_idle(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_idle),
    .ap_ready(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_ready),
    .sext_ln60_1(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_333_out),
    .sext_ln60_3(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_345_out),
    .sext_ln60_5(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_357_out),
    .sext_ln60_7(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_369_out),
    .sext_ln60_9(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3711_out),
    .sext_ln60_11(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3813_out),
    .sext_ln60_12(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_3915_out),
    .sext_ln60_14(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4017_out),
    .sext_ln60_16(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4119_out),
    .sext_ln60_18(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4221_out),
    .sext_ln60_19(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4323_out),
    .sext_ln60_20(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4425_out),
    .sext_ln60_21(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4527_out),
    .sext_ln60_23(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4629_out),
    .sext_ln60_25(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4731_out),
    .sext_ln60_27(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4833_out),
    .sext_ln60_29(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_4935_out),
    .sext_ln60_31(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5037_out),
    .sext_ln60_33(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5139_out),
    .sext_ln60_35(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5241_out),
    .sext_ln60_37(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5343_out),
    .sext_ln60_39(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5445_out),
    .sext_ln60_41(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5547_out),
    .sext_ln60_43(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5649_out),
    .sext_ln60_44(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5751_out),
    .sext_ln60_46(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5853_out),
    .sext_ln60_48(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_5955_out),
    .sext_ln60_50(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6057_out),
    .sext_ln60_52(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6159_out),
    .sext_ln60_53(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6261_out),
    .sext_ln60_54(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6363_out),
    .sext_ln60_56(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_hidden_6465_out),
    .local_output_3_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_3_out),
    .local_output_3_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_3_out_ap_vld),
    .local_output_2_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_2_out),
    .local_output_2_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_2_out_ap_vld),
    .local_output_1_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_1_out),
    .local_output_1_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_1_out_ap_vld),
    .local_output_out(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_out),
    .local_output_out_ap_vld(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_out_ap_vld)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_4 grp_object_detect_nnbw_Pipeline_4_fu_478(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start),
    .ap_done(grp_object_detect_nnbw_Pipeline_4_fu_478_ap_done),
    .ap_idle(grp_object_detect_nnbw_Pipeline_4_fu_478_ap_idle),
    .ap_ready(grp_object_detect_nnbw_Pipeline_4_fu_478_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(1'b0),
    .m_axi_gmem_0_ARADDR(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(1'b0),
    .m_axi_gmem_0_RREADY(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(16'd0),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(10'd0),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .sext_ln70(trunc_ln1_reg_937),
    .local_output_reload(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_out),
    .local_output_1_reload(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_1_out),
    .local_output_2_reload(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_2_out),
    .local_output_3_reload(grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_local_output_3_out)
);

object_detect_nnbw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .length_r(length_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

object_detect_nnbw_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(gmem_0_ARADDR),
    .I_CH0_ARLEN(gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(gmem_0_AWADDR),
    .I_CH0_AWLEN(gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WDATA),
    .I_CH0_WSTRB(grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WSTRB),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start_reg <= 1'b1;
        end else if ((grp_object_detect_nnbw_Pipeline_1_fu_324_ap_ready == 1'b1)) begin
            grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start_reg <= 1'b1;
        end else if ((grp_object_detect_nnbw_Pipeline_4_fu_478_ap_ready == 1'b1)) begin
            grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state12) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start_reg <= 1'b1;
        end else if ((grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_ready == 1'b1)) begin
            grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start_reg <= 1'b1;
        end else if ((grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_ready == 1'b1)) begin
            grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln34_reg_918 <= icmp_ln34_fu_489_p2;
        input_r_read_reg_697 <= input_r;
        length_r_read_reg_686 <= length_r;
        output_r_read_reg_692 <= output_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_cast_reg_927 <= {{input_r_read_reg_697[63:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        trunc_ln1_reg_937 <= {{output_r_read_reg_692[63:1]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if (((gmem_0_AWREADY == 1'b0) | (grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done == 1'b0))) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_object_detect_nnbw_Pipeline_4_fu_478_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln34_reg_918 == 1'd0))) begin
        gmem_0_ARADDR = p_cast_cast_fu_512_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_0_ARADDR = grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARADDR;
    end else begin
        gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln34_reg_918 == 1'd0))) begin
        gmem_0_ARLEN = zext_ln34_fu_498_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_0_ARLEN = grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARLEN;
    end else begin
        gmem_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln34_reg_918 == 1'd0))) begin
        gmem_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_0_ARVALID = grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_ARVALID;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_0_AWREADY == 1'b0) | (grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem_0_AWADDR = sext_ln70_fu_660_p1;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        gmem_0_AWADDR = grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWADDR;
    end else begin
        gmem_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((gmem_0_AWREADY == 1'b0) | (grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem_0_AWLEN = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        gmem_0_AWLEN = grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWLEN;
    end else begin
        gmem_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((gmem_0_AWREADY == 1'b0) | (grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem_0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        gmem_0_AWVALID = grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_AWVALID;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        gmem_0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        gmem_0_BREADY = grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_BREADY;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_0_RREADY = grp_object_detect_nnbw_Pipeline_1_fu_324_m_axi_gmem_0_RREADY;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        gmem_0_WVALID = grp_object_detect_nnbw_Pipeline_4_fu_478_m_axi_gmem_0_WVALID;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln34_reg_918 == 1'd0))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        local_input_address0 = grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_local_input_address0;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln34_reg_918 == 1'd0))) begin
        local_input_address0 = grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_address0;
    end else begin
        local_input_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        local_input_ce0 = grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_local_input_ce0;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln34_reg_918 == 1'd0))) begin
        local_input_ce0 = grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_ce0;
    end else begin
        local_input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln34_reg_918 == 1'd0))) begin
        local_input_we0 = grp_object_detect_nnbw_Pipeline_1_fu_324_local_input_we0;
    end else begin
        local_input_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln34_reg_918 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln34_reg_918 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if ((~((gmem_0_AWREADY == 1'b0) | (grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_object_detect_nnbw_Pipeline_4_fu_478_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_NS_fsm_state12 = ap_NS_fsm[32'd11];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_object_detect_nnbw_Pipeline_1_fu_324_ap_done == 1'b0) & (icmp_ln34_reg_918 == 1'd0));
end

always @ (*) begin
    ap_block_state2_io = ((gmem_0_ARREADY == 1'b0) & (icmp_ln34_reg_918 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start = grp_object_detect_nnbw_Pipeline_1_fu_324_ap_start_reg;

assign grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start = grp_object_detect_nnbw_Pipeline_4_fu_478_ap_start_reg;

assign grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start = grp_object_detect_nnbw_Pipeline_VITIS_LOOP_38_1_VITIS_LOOP_42_2_fu_333_ap_start_reg;

assign grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start = grp_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_fu_374_ap_start_reg;

assign icmp_ln34_fu_489_p0 = length_r;

assign icmp_ln34_fu_489_p2 = ((icmp_ln34_fu_489_p0 == 32'd0) ? 1'b1 : 1'b0);

assign p_cast_cast_fu_512_p1 = p_cast_fu_503_p4;

assign p_cast_fu_503_p4 = {{input_r_read_reg_697[63:1]}};

assign sext_ln34_fu_495_p1 = $signed(length_r_read_reg_686);

assign sext_ln70_fu_660_p1 = $signed(trunc_ln1_reg_937);

assign zext_ln34_fu_498_p1 = $unsigned(sext_ln34_fu_495_p1);

endmodule //object_detect_nnbw
