// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln60_1,
        sext_ln60_3,
        sext_ln60_5,
        sext_ln60_7,
        sext_ln60_9,
        sext_ln60_11,
        sext_ln60_12,
        sext_ln60_14,
        sext_ln60_16,
        sext_ln60_18,
        sext_ln60_19,
        sext_ln60_20,
        sext_ln60_21,
        sext_ln60_23,
        sext_ln60_25,
        sext_ln60_27,
        sext_ln60_29,
        sext_ln60_31,
        sext_ln60_33,
        sext_ln60_35,
        sext_ln60_37,
        sext_ln60_39,
        sext_ln60_41,
        sext_ln60_43,
        sext_ln60_44,
        sext_ln60_46,
        sext_ln60_48,
        sext_ln60_50,
        sext_ln60_52,
        sext_ln60_53,
        sext_ln60_54,
        sext_ln60_56,
        local_output_3_out,
        local_output_3_out_ap_vld,
        local_output_2_out,
        local_output_2_out_ap_vld,
        local_output_1_out,
        local_output_1_out_ap_vld,
        local_output_out,
        local_output_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] sext_ln60_1;
input  [15:0] sext_ln60_3;
input  [15:0] sext_ln60_5;
input  [15:0] sext_ln60_7;
input  [15:0] sext_ln60_9;
input  [15:0] sext_ln60_11;
input  [15:0] sext_ln60_12;
input  [15:0] sext_ln60_14;
input  [15:0] sext_ln60_16;
input  [15:0] sext_ln60_18;
input  [15:0] sext_ln60_19;
input  [15:0] sext_ln60_20;
input  [15:0] sext_ln60_21;
input  [15:0] sext_ln60_23;
input  [15:0] sext_ln60_25;
input  [15:0] sext_ln60_27;
input  [15:0] sext_ln60_29;
input  [15:0] sext_ln60_31;
input  [15:0] sext_ln60_33;
input  [15:0] sext_ln60_35;
input  [15:0] sext_ln60_37;
input  [15:0] sext_ln60_39;
input  [15:0] sext_ln60_41;
input  [15:0] sext_ln60_43;
input  [15:0] sext_ln60_44;
input  [15:0] sext_ln60_46;
input  [15:0] sext_ln60_48;
input  [15:0] sext_ln60_50;
input  [15:0] sext_ln60_52;
input  [15:0] sext_ln60_53;
input  [15:0] sext_ln60_54;
input  [15:0] sext_ln60_56;
output  [15:0] local_output_3_out;
output   local_output_3_out_ap_vld;
output  [15:0] local_output_2_out;
output   local_output_2_out_ap_vld;
output  [15:0] local_output_1_out;
output   local_output_1_out_ap_vld;
output  [15:0] local_output_out;
output   local_output_out_ap_vld;

reg ap_idle;
reg local_output_3_out_ap_vld;
reg local_output_2_out_ap_vld;
reg local_output_1_out_ap_vld;
reg local_output_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln54_fu_988_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] w2_0_address0;
wire  signed [15:0] w2_0_q0;
wire   [1:0] w2_1_address0;
wire  signed [15:0] w2_1_q0;
wire   [1:0] w2_2_address0;
wire  signed [15:0] w2_2_q0;
wire   [1:0] w2_3_address0;
wire  signed [15:0] w2_3_q0;
wire   [1:0] w2_4_address0;
wire  signed [15:0] w2_4_q0;
wire   [1:0] w2_5_address0;
wire  signed [15:0] w2_5_q0;
wire   [1:0] w2_6_address0;
wire   [14:0] w2_6_q0;
wire   [1:0] w2_7_address0;
wire  signed [15:0] w2_7_q0;
wire   [1:0] w2_8_address0;
wire  signed [15:0] w2_8_q0;
wire   [1:0] w2_9_address0;
wire  signed [15:0] w2_9_q0;
wire   [1:0] w2_10_address0;
wire   [14:0] w2_10_q0;
wire   [1:0] w2_11_address0;
wire  signed [14:0] w2_11_q0;
wire   [1:0] w2_12_address0;
wire  signed [15:0] w2_12_q0;
wire   [1:0] w2_13_address0;
wire  signed [15:0] w2_13_q0;
wire   [1:0] w2_14_address0;
wire  signed [15:0] w2_14_q0;
wire   [1:0] w2_15_address0;
wire  signed [15:0] w2_15_q0;
wire   [1:0] w2_16_address0;
wire  signed [15:0] w2_16_q0;
wire   [1:0] w2_17_address0;
wire  signed [15:0] w2_17_q0;
wire   [1:0] w2_18_address0;
wire  signed [15:0] w2_18_q0;
wire   [1:0] w2_19_address0;
wire  signed [15:0] w2_19_q0;
wire   [1:0] w2_20_address0;
wire  signed [15:0] w2_20_q0;
wire   [1:0] w2_21_address0;
wire  signed [15:0] w2_21_q0;
wire   [1:0] w2_22_address0;
wire  signed [15:0] w2_22_q0;
wire   [1:0] w2_23_address0;
wire   [14:0] w2_23_q0;
wire   [1:0] w2_24_address0;
wire  signed [15:0] w2_24_q0;
wire   [1:0] w2_25_address0;
wire  signed [15:0] w2_25_q0;
wire   [1:0] w2_26_address0;
wire  signed [15:0] w2_26_q0;
wire   [1:0] w2_27_address0;
wire  signed [15:0] w2_27_q0;
wire   [1:0] w2_28_address0;
wire   [14:0] w2_28_q0;
wire   [1:0] w2_29_address0;
wire   [15:0] w2_29_q0;
wire   [1:0] w2_30_address0;
wire   [15:0] w2_30_q0;
wire   [1:0] w2_31_address0;
wire   [15:0] w2_31_q0;
wire    ap_block_pp0_stage0_11001;
wire  signed [25:0] sext_ln60_56_cast_fu_852_p1;
reg  signed [25:0] sext_ln60_56_cast_reg_2028;
wire  signed [25:0] sext_ln60_54_cast_fu_856_p1;
reg  signed [25:0] sext_ln60_54_cast_reg_2033;
wire  signed [25:0] sext_ln60_53_cast_fu_860_p1;
reg  signed [25:0] sext_ln60_53_cast_reg_2038;
wire  signed [25:0] sext_ln60_52_cast_fu_864_p1;
reg  signed [25:0] sext_ln60_52_cast_reg_2043;
wire  signed [25:0] sext_ln60_50_cast_fu_868_p1;
reg  signed [25:0] sext_ln60_50_cast_reg_2048;
wire  signed [25:0] sext_ln60_48_cast_fu_872_p1;
reg  signed [25:0] sext_ln60_48_cast_reg_2053;
wire  signed [25:0] sext_ln60_46_cast_fu_876_p1;
reg  signed [25:0] sext_ln60_46_cast_reg_2058;
wire  signed [25:0] sext_ln60_44_cast_fu_880_p1;
reg  signed [25:0] sext_ln60_44_cast_reg_2063;
wire  signed [25:0] sext_ln60_43_cast_fu_884_p1;
reg  signed [25:0] sext_ln60_43_cast_reg_2068;
wire  signed [25:0] sext_ln60_41_cast_fu_888_p1;
reg  signed [25:0] sext_ln60_41_cast_reg_2073;
wire  signed [25:0] sext_ln60_39_cast_fu_892_p1;
reg  signed [25:0] sext_ln60_39_cast_reg_2078;
wire  signed [25:0] sext_ln60_37_cast_fu_896_p1;
reg  signed [25:0] sext_ln60_37_cast_reg_2083;
wire  signed [25:0] sext_ln60_35_cast_fu_900_p1;
reg  signed [25:0] sext_ln60_35_cast_reg_2088;
wire  signed [25:0] sext_ln60_33_cast_fu_904_p1;
reg  signed [25:0] sext_ln60_33_cast_reg_2093;
wire  signed [25:0] sext_ln60_31_cast_fu_908_p1;
reg  signed [25:0] sext_ln60_31_cast_reg_2098;
wire  signed [25:0] sext_ln60_29_cast_fu_912_p1;
reg  signed [25:0] sext_ln60_29_cast_reg_2103;
wire  signed [25:0] sext_ln60_27_cast_fu_916_p1;
reg  signed [25:0] sext_ln60_27_cast_reg_2108;
wire  signed [25:0] sext_ln60_25_cast_fu_920_p1;
reg  signed [25:0] sext_ln60_25_cast_reg_2113;
wire  signed [25:0] sext_ln60_23_cast_fu_924_p1;
reg  signed [25:0] sext_ln60_23_cast_reg_2118;
wire  signed [25:0] sext_ln60_21_cast_fu_928_p1;
reg  signed [25:0] sext_ln60_21_cast_reg_2123;
wire  signed [25:0] sext_ln60_20_cast_fu_932_p1;
reg  signed [25:0] sext_ln60_20_cast_reg_2128;
wire  signed [25:0] sext_ln60_19_cast_fu_936_p1;
reg  signed [25:0] sext_ln60_19_cast_reg_2133;
wire  signed [25:0] sext_ln60_18_cast_fu_940_p1;
reg  signed [25:0] sext_ln60_18_cast_reg_2138;
wire  signed [25:0] sext_ln60_16_cast_fu_944_p1;
reg  signed [25:0] sext_ln60_16_cast_reg_2143;
wire  signed [25:0] sext_ln60_14_cast_fu_948_p1;
reg  signed [25:0] sext_ln60_14_cast_reg_2148;
wire  signed [25:0] sext_ln60_12_cast_fu_952_p1;
reg  signed [25:0] sext_ln60_12_cast_reg_2153;
wire  signed [25:0] sext_ln60_11_cast_fu_956_p1;
reg  signed [25:0] sext_ln60_11_cast_reg_2158;
wire  signed [25:0] sext_ln60_9_cast_fu_960_p1;
reg  signed [25:0] sext_ln60_9_cast_reg_2163;
wire  signed [25:0] sext_ln60_7_cast_fu_964_p1;
reg  signed [25:0] sext_ln60_7_cast_reg_2168;
wire  signed [25:0] sext_ln60_5_cast_fu_968_p1;
reg  signed [25:0] sext_ln60_5_cast_reg_2173;
wire  signed [25:0] sext_ln60_3_cast_fu_972_p1;
reg  signed [25:0] sext_ln60_3_cast_reg_2178;
wire  signed [25:0] sext_ln60_1_cast_fu_976_p1;
reg  signed [25:0] sext_ln60_1_cast_reg_2183;
reg   [0:0] icmp_ln54_reg_2188;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter1_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter2_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter3_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter4_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter5_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter6_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter7_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter8_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter9_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter10_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter11_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter12_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter13_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter14_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter15_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter16_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter17_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter18_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter19_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter20_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter21_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter22_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter23_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter24_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter25_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter26_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter27_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter28_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter29_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter30_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter31_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter32_reg;
reg   [0:0] icmp_ln54_reg_2188_pp0_iter33_reg;
wire   [63:0] zext_ln54_fu_1000_p1;
reg   [63:0] zext_ln54_reg_2192;
reg   [63:0] zext_ln54_reg_2192_pp0_iter1_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter2_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter3_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter4_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter5_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter6_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter7_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter8_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter9_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter10_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter11_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter12_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter13_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter14_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter15_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter16_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter17_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter18_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter19_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter20_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter21_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter22_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter23_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter24_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter25_reg;
reg   [63:0] zext_ln54_reg_2192_pp0_iter26_reg;
wire   [1:0] trunc_ln54_fu_1005_p1;
reg   [1:0] trunc_ln54_reg_2227;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter1_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter2_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter3_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter4_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter5_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter6_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter7_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter8_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter9_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter10_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter11_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter12_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter13_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter14_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter15_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter16_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter17_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter18_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter19_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter20_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter21_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter22_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter23_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter24_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter25_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter26_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter27_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter28_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter29_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter30_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter31_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter32_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter33_reg;
reg   [1:0] trunc_ln54_reg_2227_pp0_iter34_reg;
reg  signed [14:0] w2_28_load_reg_2662;
reg   [15:0] w2_29_load_reg_2667;
reg  signed [15:0] w2_29_load_reg_2667_pp0_iter29_reg;
reg   [15:0] w2_30_load_reg_2672;
reg   [15:0] w2_30_load_reg_2672_pp0_iter29_reg;
reg  signed [15:0] w2_30_load_reg_2672_pp0_iter30_reg;
reg   [15:0] w2_31_load_reg_2677;
reg   [15:0] w2_31_load_reg_2677_pp0_iter29_reg;
reg   [15:0] w2_31_load_reg_2677_pp0_iter30_reg;
reg  signed [15:0] w2_31_load_reg_2677_pp0_iter31_reg;
wire    ap_block_pp0_stage0;
reg   [2:0] i_fu_196;
wire   [2:0] add_ln54_fu_994_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
reg   [15:0] local_output_fu_200;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg   [15:0] local_output_1_fu_204;
reg   [15:0] local_output_2_fu_208;
reg   [15:0] local_output_3_fu_212;
wire    ap_block_pp0_stage0_01001;
reg    w2_0_ce0_local;
reg    w2_1_ce0_local;
reg    w2_2_ce0_local;
reg    w2_3_ce0_local;
reg    w2_4_ce0_local;
reg    w2_5_ce0_local;
reg    w2_6_ce0_local;
reg    w2_7_ce0_local;
reg    w2_8_ce0_local;
reg    w2_9_ce0_local;
reg    w2_10_ce0_local;
reg    w2_11_ce0_local;
reg    w2_12_ce0_local;
reg    w2_13_ce0_local;
reg    w2_14_ce0_local;
reg    w2_15_ce0_local;
reg    w2_16_ce0_local;
reg    w2_17_ce0_local;
reg    w2_18_ce0_local;
reg    w2_19_ce0_local;
reg    w2_20_ce0_local;
reg    w2_21_ce0_local;
reg    w2_22_ce0_local;
reg    w2_23_ce0_local;
reg    w2_24_ce0_local;
reg    w2_25_ce0_local;
reg    w2_26_ce0_local;
reg    w2_27_ce0_local;
reg    w2_28_ce0_local;
reg    w2_29_ce0_local;
reg    w2_30_ce0_local;
reg    w2_31_ce0_local;
wire   [15:0] sum_fu_1022_p9;
wire   [15:0] sum_fu_1022_p11;
wire  signed [25:0] tmp_3_fu_1057_p1;
wire   [25:0] grp_fu_1741_p3;
wire   [15:0] tmp_3_fu_1057_p4;
wire  signed [25:0] tmp_4_fu_1078_p1;
wire   [25:0] grp_fu_1749_p3;
wire   [15:0] tmp_4_fu_1078_p4;
wire  signed [25:0] tmp_5_fu_1099_p1;
wire   [25:0] grp_fu_1757_p3;
wire   [15:0] tmp_5_fu_1099_p4;
wire  signed [25:0] tmp_6_fu_1120_p1;
wire   [25:0] grp_fu_1765_p3;
wire   [15:0] tmp_6_fu_1120_p4;
wire  signed [25:0] tmp_7_fu_1141_p1;
wire   [25:0] grp_fu_1773_p3;
wire   [15:0] tmp_7_fu_1141_p4;
wire  signed [25:0] tmp_8_fu_1162_p1;
wire   [25:0] grp_fu_1781_p3;
wire   [15:0] tmp_8_fu_1162_p4;
wire  signed [25:0] tmp_9_fu_1183_p1;
wire   [25:0] grp_fu_1789_p3;
wire   [15:0] tmp_9_fu_1183_p4;
wire  signed [25:0] tmp_s_fu_1204_p1;
wire   [25:0] grp_fu_1797_p3;
wire   [15:0] tmp_s_fu_1204_p4;
wire  signed [25:0] tmp_1_fu_1225_p1;
wire   [25:0] grp_fu_1805_p3;
wire   [15:0] tmp_1_fu_1225_p4;
wire  signed [25:0] tmp_2_fu_1246_p1;
wire   [25:0] grp_fu_1813_p3;
wire   [15:0] tmp_2_fu_1246_p4;
wire  signed [25:0] tmp_10_fu_1267_p1;
wire   [25:0] grp_fu_1821_p3;
wire   [15:0] tmp_10_fu_1267_p4;
wire  signed [25:0] tmp_11_fu_1288_p1;
wire   [25:0] grp_fu_1829_p3;
wire   [15:0] tmp_11_fu_1288_p4;
wire  signed [25:0] tmp_12_fu_1309_p1;
wire   [25:0] grp_fu_1837_p3;
wire   [15:0] tmp_12_fu_1309_p4;
wire  signed [25:0] tmp_13_fu_1330_p1;
wire   [25:0] grp_fu_1845_p3;
wire   [15:0] tmp_13_fu_1330_p4;
wire  signed [25:0] tmp_14_fu_1351_p1;
wire   [25:0] grp_fu_1853_p3;
wire   [15:0] tmp_14_fu_1351_p4;
wire  signed [25:0] tmp_15_fu_1372_p1;
wire   [25:0] grp_fu_1861_p3;
wire   [15:0] tmp_15_fu_1372_p4;
wire  signed [25:0] tmp_16_fu_1393_p1;
wire   [25:0] grp_fu_1869_p3;
wire   [15:0] tmp_16_fu_1393_p4;
wire  signed [25:0] tmp_17_fu_1414_p1;
wire   [25:0] grp_fu_1877_p3;
wire   [15:0] tmp_17_fu_1414_p4;
wire  signed [25:0] tmp_18_fu_1435_p1;
wire   [25:0] grp_fu_1885_p3;
wire   [15:0] tmp_18_fu_1435_p4;
wire  signed [25:0] tmp_19_fu_1456_p1;
wire   [25:0] grp_fu_1893_p3;
wire   [15:0] tmp_19_fu_1456_p4;
wire  signed [25:0] tmp_20_fu_1477_p1;
wire   [25:0] grp_fu_1901_p3;
wire   [15:0] tmp_20_fu_1477_p4;
wire  signed [25:0] tmp_21_fu_1498_p1;
wire   [25:0] grp_fu_1909_p3;
wire   [15:0] tmp_21_fu_1498_p4;
wire  signed [25:0] tmp_22_fu_1519_p1;
wire   [25:0] grp_fu_1917_p3;
wire   [15:0] tmp_22_fu_1519_p4;
wire  signed [25:0] tmp_23_fu_1540_p1;
wire   [25:0] grp_fu_1925_p3;
wire   [15:0] tmp_23_fu_1540_p4;
wire  signed [25:0] tmp_24_fu_1561_p1;
wire   [25:0] grp_fu_1933_p3;
wire   [15:0] tmp_24_fu_1561_p4;
wire  signed [25:0] tmp_25_fu_1582_p1;
wire   [25:0] grp_fu_1941_p3;
wire   [15:0] tmp_25_fu_1582_p4;
wire  signed [25:0] tmp_26_fu_1602_p1;
wire   [25:0] grp_fu_1949_p3;
wire   [15:0] tmp_26_fu_1602_p4;
wire  signed [25:0] tmp_27_fu_1622_p1;
wire   [25:0] grp_fu_1957_p3;
wire   [15:0] tmp_27_fu_1622_p4;
wire  signed [25:0] tmp_28_fu_1642_p1;
wire   [25:0] grp_fu_1965_p3;
wire   [15:0] tmp_28_fu_1642_p4;
wire  signed [25:0] tmp_29_fu_1662_p1;
wire   [25:0] grp_fu_1973_p3;
wire   [15:0] tmp_29_fu_1662_p4;
wire  signed [25:0] tmp_30_fu_1679_p1;
wire   [25:0] grp_fu_1981_p3;
wire   [15:0] tmp_30_fu_1679_p4;
wire  signed [25:0] local_output_4_fu_1696_p1;
wire   [25:0] grp_fu_1989_p3;
wire  signed [15:0] grp_fu_1741_p1;
wire   [25:0] grp_fu_1741_p2;
wire  signed [15:0] grp_fu_1749_p1;
wire   [25:0] grp_fu_1749_p2;
wire  signed [15:0] grp_fu_1757_p1;
wire   [25:0] grp_fu_1757_p2;
wire  signed [15:0] grp_fu_1765_p1;
wire   [25:0] grp_fu_1765_p2;
wire  signed [15:0] grp_fu_1773_p1;
wire   [25:0] grp_fu_1773_p2;
wire  signed [15:0] grp_fu_1781_p1;
wire   [25:0] grp_fu_1781_p2;
wire  signed [15:0] grp_fu_1789_p0;
wire   [14:0] grp_fu_1789_p1;
wire   [25:0] grp_fu_1789_p2;
wire  signed [15:0] grp_fu_1797_p1;
wire   [25:0] grp_fu_1797_p2;
wire  signed [15:0] grp_fu_1805_p1;
wire   [25:0] grp_fu_1805_p2;
wire  signed [15:0] grp_fu_1813_p1;
wire   [25:0] grp_fu_1813_p2;
wire  signed [15:0] grp_fu_1821_p0;
wire   [14:0] grp_fu_1821_p1;
wire   [25:0] grp_fu_1821_p2;
wire  signed [15:0] grp_fu_1829_p0;
wire   [25:0] grp_fu_1829_p2;
wire  signed [15:0] grp_fu_1837_p1;
wire   [25:0] grp_fu_1837_p2;
wire  signed [15:0] grp_fu_1845_p1;
wire   [25:0] grp_fu_1845_p2;
wire  signed [15:0] grp_fu_1853_p1;
wire   [25:0] grp_fu_1853_p2;
wire  signed [15:0] grp_fu_1861_p1;
wire   [25:0] grp_fu_1861_p2;
wire  signed [15:0] grp_fu_1869_p1;
wire   [25:0] grp_fu_1869_p2;
wire  signed [15:0] grp_fu_1877_p1;
wire   [25:0] grp_fu_1877_p2;
wire  signed [15:0] grp_fu_1885_p1;
wire   [25:0] grp_fu_1885_p2;
wire  signed [15:0] grp_fu_1893_p1;
wire   [25:0] grp_fu_1893_p2;
wire  signed [15:0] grp_fu_1901_p1;
wire   [25:0] grp_fu_1901_p2;
wire  signed [15:0] grp_fu_1909_p1;
wire   [25:0] grp_fu_1909_p2;
wire  signed [15:0] grp_fu_1917_p1;
wire   [25:0] grp_fu_1917_p2;
wire  signed [15:0] grp_fu_1925_p0;
wire   [14:0] grp_fu_1925_p1;
wire   [25:0] grp_fu_1925_p2;
wire  signed [15:0] grp_fu_1933_p1;
wire   [25:0] grp_fu_1933_p2;
wire  signed [15:0] grp_fu_1941_p1;
wire   [25:0] grp_fu_1941_p2;
wire  signed [15:0] grp_fu_1949_p1;
wire   [25:0] grp_fu_1949_p2;
wire  signed [15:0] grp_fu_1957_p1;
wire   [25:0] grp_fu_1957_p2;
wire  signed [15:0] grp_fu_1965_p0;
wire   [25:0] grp_fu_1965_p2;
wire  signed [15:0] grp_fu_1973_p1;
wire   [25:0] grp_fu_1973_p2;
wire  signed [15:0] grp_fu_1981_p1;
wire   [25:0] grp_fu_1981_p2;
wire  signed [15:0] grp_fu_1989_p1;
wire   [25:0] grp_fu_1989_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [25:0] grp_fu_1789_p10;
wire   [25:0] grp_fu_1821_p10;
wire   [25:0] grp_fu_1925_p10;
wire   [1:0] sum_fu_1022_p1;
wire   [1:0] sum_fu_1022_p3;
wire  signed [1:0] sum_fu_1022_p5;
wire  signed [1:0] sum_fu_1022_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 i_fu_196 = 3'd0;
#0 local_output_fu_200 = 16'd0;
#0 local_output_1_fu_204 = 16'd0;
#0 local_output_2_fu_208 = 16'd0;
#0 local_output_3_fu_212 = 16'd0;
#0 ap_done_reg = 1'b0;
end

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_0_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_0_address0),
    .ce0(w2_0_ce0_local),
    .q0(w2_0_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_1_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_1_address0),
    .ce0(w2_1_ce0_local),
    .q0(w2_1_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_2_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_2_address0),
    .ce0(w2_2_ce0_local),
    .q0(w2_2_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_3_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_3_address0),
    .ce0(w2_3_ce0_local),
    .q0(w2_3_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_4_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_4_address0),
    .ce0(w2_4_ce0_local),
    .q0(w2_4_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_5_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_5_address0),
    .ce0(w2_5_ce0_local),
    .q0(w2_5_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_6_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_6_address0),
    .ce0(w2_6_ce0_local),
    .q0(w2_6_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_7_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_7_address0),
    .ce0(w2_7_ce0_local),
    .q0(w2_7_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_8_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_8_address0),
    .ce0(w2_8_ce0_local),
    .q0(w2_8_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_9_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_9_address0),
    .ce0(w2_9_ce0_local),
    .q0(w2_9_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_10_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_10_address0),
    .ce0(w2_10_ce0_local),
    .q0(w2_10_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_11_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_11_address0),
    .ce0(w2_11_ce0_local),
    .q0(w2_11_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_12_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_12_address0),
    .ce0(w2_12_ce0_local),
    .q0(w2_12_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_13_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_13_address0),
    .ce0(w2_13_ce0_local),
    .q0(w2_13_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_14_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_14_address0),
    .ce0(w2_14_ce0_local),
    .q0(w2_14_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_15_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_15_address0),
    .ce0(w2_15_ce0_local),
    .q0(w2_15_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_16_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_16_address0),
    .ce0(w2_16_ce0_local),
    .q0(w2_16_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_17_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_17_address0),
    .ce0(w2_17_ce0_local),
    .q0(w2_17_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_18_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_18_address0),
    .ce0(w2_18_ce0_local),
    .q0(w2_18_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_19_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_19_address0),
    .ce0(w2_19_ce0_local),
    .q0(w2_19_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_20_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_20_address0),
    .ce0(w2_20_ce0_local),
    .q0(w2_20_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_21_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_21_address0),
    .ce0(w2_21_ce0_local),
    .q0(w2_21_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_22_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_22_address0),
    .ce0(w2_22_ce0_local),
    .q0(w2_22_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_23_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_23_address0),
    .ce0(w2_23_ce0_local),
    .q0(w2_23_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_24_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_24_address0),
    .ce0(w2_24_ce0_local),
    .q0(w2_24_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_25_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_25_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_25_address0),
    .ce0(w2_25_ce0_local),
    .q0(w2_25_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_26_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_26_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_26_address0),
    .ce0(w2_26_ce0_local),
    .q0(w2_26_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_27_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_27_address0),
    .ce0(w2_27_ce0_local),
    .q0(w2_27_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_28_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_28_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_28_address0),
    .ce0(w2_28_ce0_local),
    .q0(w2_28_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_29_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_29_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_29_address0),
    .ce0(w2_29_ce0_local),
    .q0(w2_29_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_30_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_30_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_30_address0),
    .ce0(w2_30_ce0_local),
    .q0(w2_30_q0)
);

object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3_w2_31_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w2_31_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_31_address0),
    .ce0(w2_31_ce0_local),
    .q0(w2_31_q0)
);

(* dissolve_hierarchy = "yes" *) object_detect_nnbw_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U42(
    .din0(16'd64512),
    .din1(16'd11264),
    .din2(16'd38912),
    .din3(16'd59392),
    .def(sum_fu_1022_p9),
    .sel(trunc_ln54_reg_2227_pp0_iter2_reg),
    .dout(sum_fu_1022_p11)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_0_q0),
    .din1(grp_fu_1741_p1),
    .din2(grp_fu_1741_p2),
    .ce(1'b1),
    .dout(grp_fu_1741_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_1_q0),
    .din1(grp_fu_1749_p1),
    .din2(grp_fu_1749_p2),
    .ce(1'b1),
    .dout(grp_fu_1749_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_2_q0),
    .din1(grp_fu_1757_p1),
    .din2(grp_fu_1757_p2),
    .ce(1'b1),
    .dout(grp_fu_1757_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_3_q0),
    .din1(grp_fu_1765_p1),
    .din2(grp_fu_1765_p2),
    .ce(1'b1),
    .dout(grp_fu_1765_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_4_q0),
    .din1(grp_fu_1773_p1),
    .din2(grp_fu_1773_p2),
    .ce(1'b1),
    .dout(grp_fu_1773_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_5_q0),
    .din1(grp_fu_1781_p1),
    .din2(grp_fu_1781_p2),
    .ce(1'b1),
    .dout(grp_fu_1781_p3)
);

object_detect_nnbw_mac_muladd_16s_15ns_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_15ns_26ns_26_4_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1789_p0),
    .din1(grp_fu_1789_p1),
    .din2(grp_fu_1789_p2),
    .ce(1'b1),
    .dout(grp_fu_1789_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_7_q0),
    .din1(grp_fu_1797_p1),
    .din2(grp_fu_1797_p2),
    .ce(1'b1),
    .dout(grp_fu_1797_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_8_q0),
    .din1(grp_fu_1805_p1),
    .din2(grp_fu_1805_p2),
    .ce(1'b1),
    .dout(grp_fu_1805_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_9_q0),
    .din1(grp_fu_1813_p1),
    .din2(grp_fu_1813_p2),
    .ce(1'b1),
    .dout(grp_fu_1813_p3)
);

object_detect_nnbw_mac_muladd_16s_15ns_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_15ns_26ns_26_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1821_p0),
    .din1(grp_fu_1821_p1),
    .din2(grp_fu_1821_p2),
    .ce(1'b1),
    .dout(grp_fu_1821_p3)
);

object_detect_nnbw_mac_muladd_16s_15s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_15s_26ns_26_4_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1829_p0),
    .din1(w2_11_q0),
    .din2(grp_fu_1829_p2),
    .ce(1'b1),
    .dout(grp_fu_1829_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_12_q0),
    .din1(grp_fu_1837_p1),
    .din2(grp_fu_1837_p2),
    .ce(1'b1),
    .dout(grp_fu_1837_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_13_q0),
    .din1(grp_fu_1845_p1),
    .din2(grp_fu_1845_p2),
    .ce(1'b1),
    .dout(grp_fu_1845_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_14_q0),
    .din1(grp_fu_1853_p1),
    .din2(grp_fu_1853_p2),
    .ce(1'b1),
    .dout(grp_fu_1853_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_15_q0),
    .din1(grp_fu_1861_p1),
    .din2(grp_fu_1861_p2),
    .ce(1'b1),
    .dout(grp_fu_1861_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_16_q0),
    .din1(grp_fu_1869_p1),
    .din2(grp_fu_1869_p2),
    .ce(1'b1),
    .dout(grp_fu_1869_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_17_q0),
    .din1(grp_fu_1877_p1),
    .din2(grp_fu_1877_p2),
    .ce(1'b1),
    .dout(grp_fu_1877_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_18_q0),
    .din1(grp_fu_1885_p1),
    .din2(grp_fu_1885_p2),
    .ce(1'b1),
    .dout(grp_fu_1885_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_19_q0),
    .din1(grp_fu_1893_p1),
    .din2(grp_fu_1893_p2),
    .ce(1'b1),
    .dout(grp_fu_1893_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_20_q0),
    .din1(grp_fu_1901_p1),
    .din2(grp_fu_1901_p2),
    .ce(1'b1),
    .dout(grp_fu_1901_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_21_q0),
    .din1(grp_fu_1909_p1),
    .din2(grp_fu_1909_p2),
    .ce(1'b1),
    .dout(grp_fu_1909_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_22_q0),
    .din1(grp_fu_1917_p1),
    .din2(grp_fu_1917_p2),
    .ce(1'b1),
    .dout(grp_fu_1917_p3)
);

object_detect_nnbw_mac_muladd_16s_15ns_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_15ns_26ns_26_4_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1925_p0),
    .din1(grp_fu_1925_p1),
    .din2(grp_fu_1925_p2),
    .ce(1'b1),
    .dout(grp_fu_1925_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_24_q0),
    .din1(grp_fu_1933_p1),
    .din2(grp_fu_1933_p2),
    .ce(1'b1),
    .dout(grp_fu_1933_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_25_q0),
    .din1(grp_fu_1941_p1),
    .din2(grp_fu_1941_p2),
    .ce(1'b1),
    .dout(grp_fu_1941_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_26_q0),
    .din1(grp_fu_1949_p1),
    .din2(grp_fu_1949_p2),
    .ce(1'b1),
    .dout(grp_fu_1949_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_27_q0),
    .din1(grp_fu_1957_p1),
    .din2(grp_fu_1957_p2),
    .ce(1'b1),
    .dout(grp_fu_1957_p3)
);

object_detect_nnbw_mac_muladd_16s_15s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_15s_26ns_26_4_1_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1965_p0),
    .din1(w2_28_load_reg_2662),
    .din2(grp_fu_1965_p2),
    .ce(1'b1),
    .dout(grp_fu_1965_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_29_load_reg_2667_pp0_iter29_reg),
    .din1(grp_fu_1973_p1),
    .din2(grp_fu_1973_p2),
    .ce(1'b1),
    .dout(grp_fu_1973_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_30_load_reg_2672_pp0_iter30_reg),
    .din1(grp_fu_1981_p1),
    .din2(grp_fu_1981_p2),
    .ce(1'b1),
    .dout(grp_fu_1981_p3)
);

object_detect_nnbw_mac_muladd_16s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_16s_26ns_26_4_1_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w2_31_load_reg_2677_pp0_iter31_reg),
    .din1(grp_fu_1989_p1),
    .din2(grp_fu_1989_p2),
    .ce(1'b1),
    .dout(grp_fu_1989_p3)
);

object_detect_nnbw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln54_fu_988_p2 == 1'd0))) begin
            i_fu_196 <= add_ln54_fu_994_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_196 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln54_reg_2188_pp0_iter10_reg <= icmp_ln54_reg_2188_pp0_iter9_reg;
        icmp_ln54_reg_2188_pp0_iter11_reg <= icmp_ln54_reg_2188_pp0_iter10_reg;
        icmp_ln54_reg_2188_pp0_iter12_reg <= icmp_ln54_reg_2188_pp0_iter11_reg;
        icmp_ln54_reg_2188_pp0_iter13_reg <= icmp_ln54_reg_2188_pp0_iter12_reg;
        icmp_ln54_reg_2188_pp0_iter14_reg <= icmp_ln54_reg_2188_pp0_iter13_reg;
        icmp_ln54_reg_2188_pp0_iter15_reg <= icmp_ln54_reg_2188_pp0_iter14_reg;
        icmp_ln54_reg_2188_pp0_iter16_reg <= icmp_ln54_reg_2188_pp0_iter15_reg;
        icmp_ln54_reg_2188_pp0_iter17_reg <= icmp_ln54_reg_2188_pp0_iter16_reg;
        icmp_ln54_reg_2188_pp0_iter18_reg <= icmp_ln54_reg_2188_pp0_iter17_reg;
        icmp_ln54_reg_2188_pp0_iter19_reg <= icmp_ln54_reg_2188_pp0_iter18_reg;
        icmp_ln54_reg_2188_pp0_iter20_reg <= icmp_ln54_reg_2188_pp0_iter19_reg;
        icmp_ln54_reg_2188_pp0_iter21_reg <= icmp_ln54_reg_2188_pp0_iter20_reg;
        icmp_ln54_reg_2188_pp0_iter22_reg <= icmp_ln54_reg_2188_pp0_iter21_reg;
        icmp_ln54_reg_2188_pp0_iter23_reg <= icmp_ln54_reg_2188_pp0_iter22_reg;
        icmp_ln54_reg_2188_pp0_iter24_reg <= icmp_ln54_reg_2188_pp0_iter23_reg;
        icmp_ln54_reg_2188_pp0_iter25_reg <= icmp_ln54_reg_2188_pp0_iter24_reg;
        icmp_ln54_reg_2188_pp0_iter26_reg <= icmp_ln54_reg_2188_pp0_iter25_reg;
        icmp_ln54_reg_2188_pp0_iter27_reg <= icmp_ln54_reg_2188_pp0_iter26_reg;
        icmp_ln54_reg_2188_pp0_iter28_reg <= icmp_ln54_reg_2188_pp0_iter27_reg;
        icmp_ln54_reg_2188_pp0_iter29_reg <= icmp_ln54_reg_2188_pp0_iter28_reg;
        icmp_ln54_reg_2188_pp0_iter2_reg <= icmp_ln54_reg_2188_pp0_iter1_reg;
        icmp_ln54_reg_2188_pp0_iter30_reg <= icmp_ln54_reg_2188_pp0_iter29_reg;
        icmp_ln54_reg_2188_pp0_iter31_reg <= icmp_ln54_reg_2188_pp0_iter30_reg;
        icmp_ln54_reg_2188_pp0_iter32_reg <= icmp_ln54_reg_2188_pp0_iter31_reg;
        icmp_ln54_reg_2188_pp0_iter33_reg <= icmp_ln54_reg_2188_pp0_iter32_reg;
        icmp_ln54_reg_2188_pp0_iter3_reg <= icmp_ln54_reg_2188_pp0_iter2_reg;
        icmp_ln54_reg_2188_pp0_iter4_reg <= icmp_ln54_reg_2188_pp0_iter3_reg;
        icmp_ln54_reg_2188_pp0_iter5_reg <= icmp_ln54_reg_2188_pp0_iter4_reg;
        icmp_ln54_reg_2188_pp0_iter6_reg <= icmp_ln54_reg_2188_pp0_iter5_reg;
        icmp_ln54_reg_2188_pp0_iter7_reg <= icmp_ln54_reg_2188_pp0_iter6_reg;
        icmp_ln54_reg_2188_pp0_iter8_reg <= icmp_ln54_reg_2188_pp0_iter7_reg;
        icmp_ln54_reg_2188_pp0_iter9_reg <= icmp_ln54_reg_2188_pp0_iter8_reg;
        trunc_ln54_reg_2227_pp0_iter10_reg <= trunc_ln54_reg_2227_pp0_iter9_reg;
        trunc_ln54_reg_2227_pp0_iter11_reg <= trunc_ln54_reg_2227_pp0_iter10_reg;
        trunc_ln54_reg_2227_pp0_iter12_reg <= trunc_ln54_reg_2227_pp0_iter11_reg;
        trunc_ln54_reg_2227_pp0_iter13_reg <= trunc_ln54_reg_2227_pp0_iter12_reg;
        trunc_ln54_reg_2227_pp0_iter14_reg <= trunc_ln54_reg_2227_pp0_iter13_reg;
        trunc_ln54_reg_2227_pp0_iter15_reg <= trunc_ln54_reg_2227_pp0_iter14_reg;
        trunc_ln54_reg_2227_pp0_iter16_reg <= trunc_ln54_reg_2227_pp0_iter15_reg;
        trunc_ln54_reg_2227_pp0_iter17_reg <= trunc_ln54_reg_2227_pp0_iter16_reg;
        trunc_ln54_reg_2227_pp0_iter18_reg <= trunc_ln54_reg_2227_pp0_iter17_reg;
        trunc_ln54_reg_2227_pp0_iter19_reg <= trunc_ln54_reg_2227_pp0_iter18_reg;
        trunc_ln54_reg_2227_pp0_iter20_reg <= trunc_ln54_reg_2227_pp0_iter19_reg;
        trunc_ln54_reg_2227_pp0_iter21_reg <= trunc_ln54_reg_2227_pp0_iter20_reg;
        trunc_ln54_reg_2227_pp0_iter22_reg <= trunc_ln54_reg_2227_pp0_iter21_reg;
        trunc_ln54_reg_2227_pp0_iter23_reg <= trunc_ln54_reg_2227_pp0_iter22_reg;
        trunc_ln54_reg_2227_pp0_iter24_reg <= trunc_ln54_reg_2227_pp0_iter23_reg;
        trunc_ln54_reg_2227_pp0_iter25_reg <= trunc_ln54_reg_2227_pp0_iter24_reg;
        trunc_ln54_reg_2227_pp0_iter26_reg <= trunc_ln54_reg_2227_pp0_iter25_reg;
        trunc_ln54_reg_2227_pp0_iter27_reg <= trunc_ln54_reg_2227_pp0_iter26_reg;
        trunc_ln54_reg_2227_pp0_iter28_reg <= trunc_ln54_reg_2227_pp0_iter27_reg;
        trunc_ln54_reg_2227_pp0_iter29_reg <= trunc_ln54_reg_2227_pp0_iter28_reg;
        trunc_ln54_reg_2227_pp0_iter2_reg <= trunc_ln54_reg_2227_pp0_iter1_reg;
        trunc_ln54_reg_2227_pp0_iter30_reg <= trunc_ln54_reg_2227_pp0_iter29_reg;
        trunc_ln54_reg_2227_pp0_iter31_reg <= trunc_ln54_reg_2227_pp0_iter30_reg;
        trunc_ln54_reg_2227_pp0_iter32_reg <= trunc_ln54_reg_2227_pp0_iter31_reg;
        trunc_ln54_reg_2227_pp0_iter33_reg <= trunc_ln54_reg_2227_pp0_iter32_reg;
        trunc_ln54_reg_2227_pp0_iter34_reg <= trunc_ln54_reg_2227_pp0_iter33_reg;
        trunc_ln54_reg_2227_pp0_iter3_reg <= trunc_ln54_reg_2227_pp0_iter2_reg;
        trunc_ln54_reg_2227_pp0_iter4_reg <= trunc_ln54_reg_2227_pp0_iter3_reg;
        trunc_ln54_reg_2227_pp0_iter5_reg <= trunc_ln54_reg_2227_pp0_iter4_reg;
        trunc_ln54_reg_2227_pp0_iter6_reg <= trunc_ln54_reg_2227_pp0_iter5_reg;
        trunc_ln54_reg_2227_pp0_iter7_reg <= trunc_ln54_reg_2227_pp0_iter6_reg;
        trunc_ln54_reg_2227_pp0_iter8_reg <= trunc_ln54_reg_2227_pp0_iter7_reg;
        trunc_ln54_reg_2227_pp0_iter9_reg <= trunc_ln54_reg_2227_pp0_iter8_reg;
        w2_28_load_reg_2662 <= w2_28_q0;
        w2_29_load_reg_2667 <= w2_29_q0;
        w2_29_load_reg_2667_pp0_iter29_reg <= w2_29_load_reg_2667;
        w2_30_load_reg_2672 <= w2_30_q0;
        w2_30_load_reg_2672_pp0_iter29_reg <= w2_30_load_reg_2672;
        w2_30_load_reg_2672_pp0_iter30_reg <= w2_30_load_reg_2672_pp0_iter29_reg;
        w2_31_load_reg_2677 <= w2_31_q0;
        w2_31_load_reg_2677_pp0_iter29_reg <= w2_31_load_reg_2677;
        w2_31_load_reg_2677_pp0_iter30_reg <= w2_31_load_reg_2677_pp0_iter29_reg;
        w2_31_load_reg_2677_pp0_iter31_reg <= w2_31_load_reg_2677_pp0_iter30_reg;
        zext_ln54_reg_2192_pp0_iter10_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter9_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter11_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter10_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter12_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter11_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter13_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter12_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter14_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter13_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter15_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter14_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter16_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter15_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter17_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter16_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter18_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter17_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter19_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter18_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter20_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter19_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter21_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter20_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter22_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter21_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter23_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter22_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter24_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter23_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter25_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter24_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter26_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter25_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter2_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter1_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter3_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter2_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter4_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter3_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter5_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter4_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter6_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter5_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter7_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter6_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter8_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter7_reg[2 : 0];
        zext_ln54_reg_2192_pp0_iter9_reg[2 : 0] <= zext_ln54_reg_2192_pp0_iter8_reg[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln54_reg_2188 <= icmp_ln54_fu_988_p2;
        icmp_ln54_reg_2188_pp0_iter1_reg <= icmp_ln54_reg_2188;
        sext_ln60_11_cast_reg_2158 <= sext_ln60_11_cast_fu_956_p1;
        sext_ln60_12_cast_reg_2153 <= sext_ln60_12_cast_fu_952_p1;
        sext_ln60_14_cast_reg_2148 <= sext_ln60_14_cast_fu_948_p1;
        sext_ln60_16_cast_reg_2143 <= sext_ln60_16_cast_fu_944_p1;
        sext_ln60_18_cast_reg_2138 <= sext_ln60_18_cast_fu_940_p1;
        sext_ln60_19_cast_reg_2133 <= sext_ln60_19_cast_fu_936_p1;
        sext_ln60_1_cast_reg_2183 <= sext_ln60_1_cast_fu_976_p1;
        sext_ln60_20_cast_reg_2128 <= sext_ln60_20_cast_fu_932_p1;
        sext_ln60_21_cast_reg_2123 <= sext_ln60_21_cast_fu_928_p1;
        sext_ln60_23_cast_reg_2118 <= sext_ln60_23_cast_fu_924_p1;
        sext_ln60_25_cast_reg_2113 <= sext_ln60_25_cast_fu_920_p1;
        sext_ln60_27_cast_reg_2108 <= sext_ln60_27_cast_fu_916_p1;
        sext_ln60_29_cast_reg_2103 <= sext_ln60_29_cast_fu_912_p1;
        sext_ln60_31_cast_reg_2098 <= sext_ln60_31_cast_fu_908_p1;
        sext_ln60_33_cast_reg_2093 <= sext_ln60_33_cast_fu_904_p1;
        sext_ln60_35_cast_reg_2088 <= sext_ln60_35_cast_fu_900_p1;
        sext_ln60_37_cast_reg_2083 <= sext_ln60_37_cast_fu_896_p1;
        sext_ln60_39_cast_reg_2078 <= sext_ln60_39_cast_fu_892_p1;
        sext_ln60_3_cast_reg_2178 <= sext_ln60_3_cast_fu_972_p1;
        sext_ln60_41_cast_reg_2073 <= sext_ln60_41_cast_fu_888_p1;
        sext_ln60_43_cast_reg_2068 <= sext_ln60_43_cast_fu_884_p1;
        sext_ln60_44_cast_reg_2063 <= sext_ln60_44_cast_fu_880_p1;
        sext_ln60_46_cast_reg_2058 <= sext_ln60_46_cast_fu_876_p1;
        sext_ln60_48_cast_reg_2053 <= sext_ln60_48_cast_fu_872_p1;
        sext_ln60_50_cast_reg_2048 <= sext_ln60_50_cast_fu_868_p1;
        sext_ln60_52_cast_reg_2043 <= sext_ln60_52_cast_fu_864_p1;
        sext_ln60_53_cast_reg_2038 <= sext_ln60_53_cast_fu_860_p1;
        sext_ln60_54_cast_reg_2033 <= sext_ln60_54_cast_fu_856_p1;
        sext_ln60_56_cast_reg_2028 <= sext_ln60_56_cast_fu_852_p1;
        sext_ln60_5_cast_reg_2173 <= sext_ln60_5_cast_fu_968_p1;
        sext_ln60_7_cast_reg_2168 <= sext_ln60_7_cast_fu_964_p1;
        sext_ln60_9_cast_reg_2163 <= sext_ln60_9_cast_fu_960_p1;
        trunc_ln54_reg_2227 <= trunc_ln54_fu_1005_p1;
        trunc_ln54_reg_2227_pp0_iter1_reg <= trunc_ln54_reg_2227;
        zext_ln54_reg_2192[2 : 0] <= zext_ln54_fu_1000_p1[2 : 0];
        zext_ln54_reg_2192_pp0_iter1_reg[2 : 0] <= zext_ln54_reg_2192[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1) & (trunc_ln54_reg_2227_pp0_iter34_reg == 2'd1))) begin
        local_output_1_fu_204 <= {{local_output_4_fu_1696_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1) & (trunc_ln54_reg_2227_pp0_iter34_reg == 2'd2))) begin
        local_output_2_fu_208 <= {{local_output_4_fu_1696_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1) & (trunc_ln54_reg_2227_pp0_iter34_reg == 2'd3))) begin
        local_output_3_fu_212 <= {{local_output_4_fu_1696_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1) & (trunc_ln54_reg_2227_pp0_iter34_reg == 2'd0))) begin
        local_output_fu_200 <= {{local_output_4_fu_1696_p1[25:10]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln54_fu_988_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) 
    & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_196;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln54_reg_2188_pp0_iter33_reg == 1'd1))) begin
        local_output_1_out_ap_vld = 1'b1;
    end else begin
        local_output_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln54_reg_2188_pp0_iter33_reg == 1'd1))) begin
        local_output_2_out_ap_vld = 1'b1;
    end else begin
        local_output_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln54_reg_2188_pp0_iter33_reg == 1'd1))) begin
        local_output_3_out_ap_vld = 1'b1;
    end else begin
        local_output_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln54_reg_2188_pp0_iter33_reg == 1'd1))) begin
        local_output_out_ap_vld = 1'b1;
    end else begin
        local_output_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_0_ce0_local = 1'b1;
    end else begin
        w2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_10_ce0_local = 1'b1;
    end else begin
        w2_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_11_ce0_local = 1'b1;
    end else begin
        w2_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_12_ce0_local = 1'b1;
    end else begin
        w2_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_13_ce0_local = 1'b1;
    end else begin
        w2_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_14_ce0_local = 1'b1;
    end else begin
        w2_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_15_ce0_local = 1'b1;
    end else begin
        w2_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_16_ce0_local = 1'b1;
    end else begin
        w2_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_17_ce0_local = 1'b1;
    end else begin
        w2_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_18_ce0_local = 1'b1;
    end else begin
        w2_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_19_ce0_local = 1'b1;
    end else begin
        w2_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_1_ce0_local = 1'b1;
    end else begin
        w2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_20_ce0_local = 1'b1;
    end else begin
        w2_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_21_ce0_local = 1'b1;
    end else begin
        w2_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_22_ce0_local = 1'b1;
    end else begin
        w2_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_23_ce0_local = 1'b1;
    end else begin
        w2_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_24_ce0_local = 1'b1;
    end else begin
        w2_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_25_ce0_local = 1'b1;
    end else begin
        w2_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_26_ce0_local = 1'b1;
    end else begin
        w2_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        w2_27_ce0_local = 1'b1;
    end else begin
        w2_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        w2_28_ce0_local = 1'b1;
    end else begin
        w2_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        w2_29_ce0_local = 1'b1;
    end else begin
        w2_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_2_ce0_local = 1'b1;
    end else begin
        w2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        w2_30_ce0_local = 1'b1;
    end else begin
        w2_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        w2_31_ce0_local = 1'b1;
    end else begin
        w2_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_3_ce0_local = 1'b1;
    end else begin
        w2_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_4_ce0_local = 1'b1;
    end else begin
        w2_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_5_ce0_local = 1'b1;
    end else begin
        w2_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_6_ce0_local = 1'b1;
    end else begin
        w2_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_7_ce0_local = 1'b1;
    end else begin
        w2_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_8_ce0_local = 1'b1;
    end else begin
        w2_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_9_ce0_local = 1'b1;
    end else begin
        w2_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln54_fu_994_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_1741_p1 = sext_ln60_1_cast_reg_2183;

assign grp_fu_1741_p2 = {{sum_fu_1022_p11}, {10'd0}};

assign grp_fu_1749_p1 = sext_ln60_3_cast_reg_2178;

assign grp_fu_1749_p2 = {{tmp_3_fu_1057_p4}, {10'd0}};

assign grp_fu_1757_p1 = sext_ln60_5_cast_reg_2173;

assign grp_fu_1757_p2 = {{tmp_4_fu_1078_p4}, {10'd0}};

assign grp_fu_1765_p1 = sext_ln60_7_cast_reg_2168;

assign grp_fu_1765_p2 = {{tmp_5_fu_1099_p4}, {10'd0}};

assign grp_fu_1773_p1 = sext_ln60_9_cast_reg_2163;

assign grp_fu_1773_p2 = {{tmp_6_fu_1120_p4}, {10'd0}};

assign grp_fu_1781_p1 = sext_ln60_11_cast_reg_2158;

assign grp_fu_1781_p2 = {{tmp_7_fu_1141_p4}, {10'd0}};

assign grp_fu_1789_p0 = sext_ln60_12_cast_reg_2153;

assign grp_fu_1789_p1 = grp_fu_1789_p10;

assign grp_fu_1789_p10 = w2_6_q0;

assign grp_fu_1789_p2 = {{tmp_8_fu_1162_p4}, {10'd0}};

assign grp_fu_1797_p1 = sext_ln60_14_cast_reg_2148;

assign grp_fu_1797_p2 = {{tmp_9_fu_1183_p4}, {10'd0}};

assign grp_fu_1805_p1 = sext_ln60_16_cast_reg_2143;

assign grp_fu_1805_p2 = {{tmp_s_fu_1204_p4}, {10'd0}};

assign grp_fu_1813_p1 = sext_ln60_18_cast_reg_2138;

assign grp_fu_1813_p2 = {{tmp_1_fu_1225_p4}, {10'd0}};

assign grp_fu_1821_p0 = sext_ln60_19_cast_reg_2133;

assign grp_fu_1821_p1 = grp_fu_1821_p10;

assign grp_fu_1821_p10 = w2_10_q0;

assign grp_fu_1821_p2 = {{tmp_2_fu_1246_p4}, {10'd0}};

assign grp_fu_1829_p0 = sext_ln60_20_cast_reg_2128;

assign grp_fu_1829_p2 = {{tmp_10_fu_1267_p4}, {10'd0}};

assign grp_fu_1837_p1 = sext_ln60_21_cast_reg_2123;

assign grp_fu_1837_p2 = {{tmp_11_fu_1288_p4}, {10'd0}};

assign grp_fu_1845_p1 = sext_ln60_23_cast_reg_2118;

assign grp_fu_1845_p2 = {{tmp_12_fu_1309_p4}, {10'd0}};

assign grp_fu_1853_p1 = sext_ln60_25_cast_reg_2113;

assign grp_fu_1853_p2 = {{tmp_13_fu_1330_p4}, {10'd0}};

assign grp_fu_1861_p1 = sext_ln60_27_cast_reg_2108;

assign grp_fu_1861_p2 = {{tmp_14_fu_1351_p4}, {10'd0}};

assign grp_fu_1869_p1 = sext_ln60_29_cast_reg_2103;

assign grp_fu_1869_p2 = {{tmp_15_fu_1372_p4}, {10'd0}};

assign grp_fu_1877_p1 = sext_ln60_31_cast_reg_2098;

assign grp_fu_1877_p2 = {{tmp_16_fu_1393_p4}, {10'd0}};

assign grp_fu_1885_p1 = sext_ln60_33_cast_reg_2093;

assign grp_fu_1885_p2 = {{tmp_17_fu_1414_p4}, {10'd0}};

assign grp_fu_1893_p1 = sext_ln60_35_cast_reg_2088;

assign grp_fu_1893_p2 = {{tmp_18_fu_1435_p4}, {10'd0}};

assign grp_fu_1901_p1 = sext_ln60_37_cast_reg_2083;

assign grp_fu_1901_p2 = {{tmp_19_fu_1456_p4}, {10'd0}};

assign grp_fu_1909_p1 = sext_ln60_39_cast_reg_2078;

assign grp_fu_1909_p2 = {{tmp_20_fu_1477_p4}, {10'd0}};

assign grp_fu_1917_p1 = sext_ln60_41_cast_reg_2073;

assign grp_fu_1917_p2 = {{tmp_21_fu_1498_p4}, {10'd0}};

assign grp_fu_1925_p0 = sext_ln60_43_cast_reg_2068;

assign grp_fu_1925_p1 = grp_fu_1925_p10;

assign grp_fu_1925_p10 = w2_23_q0;

assign grp_fu_1925_p2 = {{tmp_22_fu_1519_p4}, {10'd0}};

assign grp_fu_1933_p1 = sext_ln60_44_cast_reg_2063;

assign grp_fu_1933_p2 = {{tmp_23_fu_1540_p4}, {10'd0}};

assign grp_fu_1941_p1 = sext_ln60_46_cast_reg_2058;

assign grp_fu_1941_p2 = {{tmp_24_fu_1561_p4}, {10'd0}};

assign grp_fu_1949_p1 = sext_ln60_48_cast_reg_2053;

assign grp_fu_1949_p2 = {{tmp_25_fu_1582_p4}, {10'd0}};

assign grp_fu_1957_p1 = sext_ln60_50_cast_reg_2048;

assign grp_fu_1957_p2 = {{tmp_26_fu_1602_p4}, {10'd0}};

assign grp_fu_1965_p0 = sext_ln60_52_cast_reg_2043;

assign grp_fu_1965_p2 = {{tmp_27_fu_1622_p4}, {10'd0}};

assign grp_fu_1973_p1 = sext_ln60_53_cast_reg_2038;

assign grp_fu_1973_p2 = {{tmp_28_fu_1642_p4}, {10'd0}};

assign grp_fu_1981_p1 = sext_ln60_54_cast_reg_2033;

assign grp_fu_1981_p2 = {{tmp_29_fu_1662_p4}, {10'd0}};

assign grp_fu_1989_p1 = sext_ln60_56_cast_reg_2028;

assign grp_fu_1989_p2 = {{tmp_30_fu_1679_p4}, {10'd0}};

assign icmp_ln54_fu_988_p2 = ((ap_sig_allocacmp_i_1 == 3'd4) ? 1'b1 : 1'b0);

assign local_output_1_out = local_output_1_fu_204;

assign local_output_2_out = local_output_2_fu_208;

assign local_output_3_out = local_output_3_fu_212;

assign local_output_4_fu_1696_p1 = grp_fu_1989_p3;

assign local_output_out = local_output_fu_200;

assign sext_ln60_11_cast_fu_956_p1 = $signed(sext_ln60_11);

assign sext_ln60_12_cast_fu_952_p1 = $signed(sext_ln60_12);

assign sext_ln60_14_cast_fu_948_p1 = $signed(sext_ln60_14);

assign sext_ln60_16_cast_fu_944_p1 = $signed(sext_ln60_16);

assign sext_ln60_18_cast_fu_940_p1 = $signed(sext_ln60_18);

assign sext_ln60_19_cast_fu_936_p1 = $signed(sext_ln60_19);

assign sext_ln60_1_cast_fu_976_p1 = $signed(sext_ln60_1);

assign sext_ln60_20_cast_fu_932_p1 = $signed(sext_ln60_20);

assign sext_ln60_21_cast_fu_928_p1 = $signed(sext_ln60_21);

assign sext_ln60_23_cast_fu_924_p1 = $signed(sext_ln60_23);

assign sext_ln60_25_cast_fu_920_p1 = $signed(sext_ln60_25);

assign sext_ln60_27_cast_fu_916_p1 = $signed(sext_ln60_27);

assign sext_ln60_29_cast_fu_912_p1 = $signed(sext_ln60_29);

assign sext_ln60_31_cast_fu_908_p1 = $signed(sext_ln60_31);

assign sext_ln60_33_cast_fu_904_p1 = $signed(sext_ln60_33);

assign sext_ln60_35_cast_fu_900_p1 = $signed(sext_ln60_35);

assign sext_ln60_37_cast_fu_896_p1 = $signed(sext_ln60_37);

assign sext_ln60_39_cast_fu_892_p1 = $signed(sext_ln60_39);

assign sext_ln60_3_cast_fu_972_p1 = $signed(sext_ln60_3);

assign sext_ln60_41_cast_fu_888_p1 = $signed(sext_ln60_41);

assign sext_ln60_43_cast_fu_884_p1 = $signed(sext_ln60_43);

assign sext_ln60_44_cast_fu_880_p1 = $signed(sext_ln60_44);

assign sext_ln60_46_cast_fu_876_p1 = $signed(sext_ln60_46);

assign sext_ln60_48_cast_fu_872_p1 = $signed(sext_ln60_48);

assign sext_ln60_50_cast_fu_868_p1 = $signed(sext_ln60_50);

assign sext_ln60_52_cast_fu_864_p1 = $signed(sext_ln60_52);

assign sext_ln60_53_cast_fu_860_p1 = $signed(sext_ln60_53);

assign sext_ln60_54_cast_fu_856_p1 = $signed(sext_ln60_54);

assign sext_ln60_56_cast_fu_852_p1 = $signed(sext_ln60_56);

assign sext_ln60_5_cast_fu_968_p1 = $signed(sext_ln60_5);

assign sext_ln60_7_cast_fu_964_p1 = $signed(sext_ln60_7);

assign sext_ln60_9_cast_fu_960_p1 = $signed(sext_ln60_9);

assign sum_fu_1022_p9 = 'bx;

assign tmp_10_fu_1267_p1 = grp_fu_1821_p3;

assign tmp_10_fu_1267_p4 = {{tmp_10_fu_1267_p1[25:10]}};

assign tmp_11_fu_1288_p1 = grp_fu_1829_p3;

assign tmp_11_fu_1288_p4 = {{tmp_11_fu_1288_p1[25:10]}};

assign tmp_12_fu_1309_p1 = grp_fu_1837_p3;

assign tmp_12_fu_1309_p4 = {{tmp_12_fu_1309_p1[25:10]}};

assign tmp_13_fu_1330_p1 = grp_fu_1845_p3;

assign tmp_13_fu_1330_p4 = {{tmp_13_fu_1330_p1[25:10]}};

assign tmp_14_fu_1351_p1 = grp_fu_1853_p3;

assign tmp_14_fu_1351_p4 = {{tmp_14_fu_1351_p1[25:10]}};

assign tmp_15_fu_1372_p1 = grp_fu_1861_p3;

assign tmp_15_fu_1372_p4 = {{tmp_15_fu_1372_p1[25:10]}};

assign tmp_16_fu_1393_p1 = grp_fu_1869_p3;

assign tmp_16_fu_1393_p4 = {{tmp_16_fu_1393_p1[25:10]}};

assign tmp_17_fu_1414_p1 = grp_fu_1877_p3;

assign tmp_17_fu_1414_p4 = {{tmp_17_fu_1414_p1[25:10]}};

assign tmp_18_fu_1435_p1 = grp_fu_1885_p3;

assign tmp_18_fu_1435_p4 = {{tmp_18_fu_1435_p1[25:10]}};

assign tmp_19_fu_1456_p1 = grp_fu_1893_p3;

assign tmp_19_fu_1456_p4 = {{tmp_19_fu_1456_p1[25:10]}};

assign tmp_1_fu_1225_p1 = grp_fu_1805_p3;

assign tmp_1_fu_1225_p4 = {{tmp_1_fu_1225_p1[25:10]}};

assign tmp_20_fu_1477_p1 = grp_fu_1901_p3;

assign tmp_20_fu_1477_p4 = {{tmp_20_fu_1477_p1[25:10]}};

assign tmp_21_fu_1498_p1 = grp_fu_1909_p3;

assign tmp_21_fu_1498_p4 = {{tmp_21_fu_1498_p1[25:10]}};

assign tmp_22_fu_1519_p1 = grp_fu_1917_p3;

assign tmp_22_fu_1519_p4 = {{tmp_22_fu_1519_p1[25:10]}};

assign tmp_23_fu_1540_p1 = grp_fu_1925_p3;

assign tmp_23_fu_1540_p4 = {{tmp_23_fu_1540_p1[25:10]}};

assign tmp_24_fu_1561_p1 = grp_fu_1933_p3;

assign tmp_24_fu_1561_p4 = {{tmp_24_fu_1561_p1[25:10]}};

assign tmp_25_fu_1582_p1 = grp_fu_1941_p3;

assign tmp_25_fu_1582_p4 = {{tmp_25_fu_1582_p1[25:10]}};

assign tmp_26_fu_1602_p1 = grp_fu_1949_p3;

assign tmp_26_fu_1602_p4 = {{tmp_26_fu_1602_p1[25:10]}};

assign tmp_27_fu_1622_p1 = grp_fu_1957_p3;

assign tmp_27_fu_1622_p4 = {{tmp_27_fu_1622_p1[25:10]}};

assign tmp_28_fu_1642_p1 = grp_fu_1965_p3;

assign tmp_28_fu_1642_p4 = {{tmp_28_fu_1642_p1[25:10]}};

assign tmp_29_fu_1662_p1 = grp_fu_1973_p3;

assign tmp_29_fu_1662_p4 = {{tmp_29_fu_1662_p1[25:10]}};

assign tmp_2_fu_1246_p1 = grp_fu_1813_p3;

assign tmp_2_fu_1246_p4 = {{tmp_2_fu_1246_p1[25:10]}};

assign tmp_30_fu_1679_p1 = grp_fu_1981_p3;

assign tmp_30_fu_1679_p4 = {{tmp_30_fu_1679_p1[25:10]}};

assign tmp_3_fu_1057_p1 = grp_fu_1741_p3;

assign tmp_3_fu_1057_p4 = {{tmp_3_fu_1057_p1[25:10]}};

assign tmp_4_fu_1078_p1 = grp_fu_1749_p3;

assign tmp_4_fu_1078_p4 = {{tmp_4_fu_1078_p1[25:10]}};

assign tmp_5_fu_1099_p1 = grp_fu_1757_p3;

assign tmp_5_fu_1099_p4 = {{tmp_5_fu_1099_p1[25:10]}};

assign tmp_6_fu_1120_p1 = grp_fu_1765_p3;

assign tmp_6_fu_1120_p4 = {{tmp_6_fu_1120_p1[25:10]}};

assign tmp_7_fu_1141_p1 = grp_fu_1773_p3;

assign tmp_7_fu_1141_p4 = {{tmp_7_fu_1141_p1[25:10]}};

assign tmp_8_fu_1162_p1 = grp_fu_1781_p3;

assign tmp_8_fu_1162_p4 = {{tmp_8_fu_1162_p1[25:10]}};

assign tmp_9_fu_1183_p1 = grp_fu_1789_p3;

assign tmp_9_fu_1183_p4 = {{tmp_9_fu_1183_p1[25:10]}};

assign tmp_s_fu_1204_p1 = grp_fu_1797_p3;

assign tmp_s_fu_1204_p4 = {{tmp_s_fu_1204_p1[25:10]}};

assign trunc_ln54_fu_1005_p1 = ap_sig_allocacmp_i_1[1:0];

assign w2_0_address0 = zext_ln54_fu_1000_p1;

assign w2_10_address0 = zext_ln54_reg_2192_pp0_iter9_reg;

assign w2_11_address0 = zext_ln54_reg_2192_pp0_iter10_reg;

assign w2_12_address0 = zext_ln54_reg_2192_pp0_iter11_reg;

assign w2_13_address0 = zext_ln54_reg_2192_pp0_iter12_reg;

assign w2_14_address0 = zext_ln54_reg_2192_pp0_iter13_reg;

assign w2_15_address0 = zext_ln54_reg_2192_pp0_iter14_reg;

assign w2_16_address0 = zext_ln54_reg_2192_pp0_iter15_reg;

assign w2_17_address0 = zext_ln54_reg_2192_pp0_iter16_reg;

assign w2_18_address0 = zext_ln54_reg_2192_pp0_iter17_reg;

assign w2_19_address0 = zext_ln54_reg_2192_pp0_iter18_reg;

assign w2_1_address0 = zext_ln54_reg_2192;

assign w2_20_address0 = zext_ln54_reg_2192_pp0_iter19_reg;

assign w2_21_address0 = zext_ln54_reg_2192_pp0_iter20_reg;

assign w2_22_address0 = zext_ln54_reg_2192_pp0_iter21_reg;

assign w2_23_address0 = zext_ln54_reg_2192_pp0_iter22_reg;

assign w2_24_address0 = zext_ln54_reg_2192_pp0_iter23_reg;

assign w2_25_address0 = zext_ln54_reg_2192_pp0_iter24_reg;

assign w2_26_address0 = zext_ln54_reg_2192_pp0_iter25_reg;

assign w2_27_address0 = zext_ln54_reg_2192_pp0_iter26_reg;

assign w2_28_address0 = zext_ln54_reg_2192_pp0_iter26_reg;

assign w2_29_address0 = zext_ln54_reg_2192_pp0_iter26_reg;

assign w2_2_address0 = zext_ln54_reg_2192_pp0_iter1_reg;

assign w2_30_address0 = zext_ln54_reg_2192_pp0_iter26_reg;

assign w2_31_address0 = zext_ln54_reg_2192_pp0_iter26_reg;

assign w2_3_address0 = zext_ln54_reg_2192_pp0_iter2_reg;

assign w2_4_address0 = zext_ln54_reg_2192_pp0_iter3_reg;

assign w2_5_address0 = zext_ln54_reg_2192_pp0_iter4_reg;

assign w2_6_address0 = zext_ln54_reg_2192_pp0_iter5_reg;

assign w2_7_address0 = zext_ln54_reg_2192_pp0_iter6_reg;

assign w2_8_address0 = zext_ln54_reg_2192_pp0_iter7_reg;

assign w2_9_address0 = zext_ln54_reg_2192_pp0_iter8_reg;

assign zext_ln54_fu_1000_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln54_reg_2192[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter1_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter2_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter3_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter4_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter5_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter6_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter7_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter8_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter9_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter10_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter11_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter12_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter13_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter14_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter15_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter16_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter17_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter18_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter19_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter20_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter21_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter22_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter23_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter24_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter25_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln54_reg_2192_pp0_iter26_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //object_detect_nnbw_object_detect_nnbw_Pipeline_VITIS_LOOP_54_3
